### ISSUE TITLE
paragraph spacing

### ISSUE THREAD

**Issue by juripfammatter** [MeierTobias/eth-summary-template#7]
Find a clean way to introduce spacing inbetween paragraphs
* \vspace*{4pt}
* \\
* \par (is obsolete because \parskip=0pt)

**Comment by MeierTobias** [comment]
Solved with the \newpar command as discussed
https://github.com/MeierTobias/eth-summary-template/blob/058682e1094431ad27aeb9db3b6bdb3c0e55e244/headers/standard_header.tex#L42
